"""Initial migration

Revision ID: b5a9ae9dc438
Revises: 
Create Date: 2025-12-16 21:45:31.311754

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b5a9ae9dc438'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('profiles',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('external_id', sa.String(), nullable=False),
    sa.Column('full_name', sa.String(), nullable=False),
    sa.Column('current_title', sa.String(), nullable=True),
    sa.Column('current_company', sa.String(), nullable=True),
    sa.Column('location_state', sa.String(length=2), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_profiles_external_id'), 'profiles', ['external_id'], unique=True)
    op.create_index(op.f('ix_profiles_location_state'), 'profiles', ['location_state'], unique=False)
    op.create_table('tracking_metadata',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('target_companies', sa.JSON(), nullable=False),
    sa.Column('target_states', sa.JSON(), nullable=False),
    sa.Column('last_ingestion', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_detection', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('education',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('profile_id', sa.String(), nullable=False),
    sa.Column('institution', sa.String(), nullable=False),
    sa.Column('graduation_year', sa.Integer(), nullable=True),
    sa.Column('degree_type', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['profile_id'], ['profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_education_profile_id'), 'education', ['profile_id'], unique=False)
    op.create_table('founder_events',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('profile_id', sa.String(), nullable=False),
    sa.Column('old_title', sa.String(), nullable=True),
    sa.Column('new_title', sa.String(), nullable=False),
    sa.Column('new_company', sa.String(), nullable=True),
    sa.Column('detected_at', sa.Date(), server_default=sa.text('(CURRENT_DATE)'), nullable=False),
    sa.Column('notified', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['profile_id'], ['profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_founder_events_detected_at'), 'founder_events', ['detected_at'], unique=False)
    op.create_index(op.f('ix_founder_events_notified'), 'founder_events', ['notified'], unique=False)
    op.create_index(op.f('ix_founder_events_profile_id'), 'founder_events', ['profile_id'], unique=False)
    op.create_table('work_history',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('profile_id', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('company', sa.String(), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('is_current', sa.Boolean(), nullable=False),
    sa.Column('snapshot_date', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['profile_id'], ['profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_work_history_profile_id'), 'work_history', ['profile_id'], unique=False)
    op.create_index(op.f('ix_work_history_snapshot_date'), 'work_history', ['snapshot_date'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_work_history_snapshot_date'), table_name='work_history')
    op.drop_index(op.f('ix_work_history_profile_id'), table_name='work_history')
    op.drop_table('work_history')
    op.drop_index(op.f('ix_founder_events_profile_id'), table_name='founder_events')
    op.drop_index(op.f('ix_founder_events_notified'), table_name='founder_events')
    op.drop_index(op.f('ix_founder_events_detected_at'), table_name='founder_events')
    op.drop_table('founder_events')
    op.drop_index(op.f('ix_education_profile_id'), table_name='education')
    op.drop_table('education')
    op.drop_table('tracking_metadata')
    op.drop_index(op.f('ix_profiles_location_state'), table_name='profiles')
    op.drop_index(op.f('ix_profiles_external_id'), table_name='profiles')
    op.drop_table('profiles')
    # ### end Alembic commands ###
